version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'mini_project'
      MYSQL_USER: 'hsh'
      MYSQL_PASSWORD: '@Aa82851620'
      MYSQL_ROOT_PASSWORD: '@Aa82851620'  # 请确保安全性
    ports:
      - '3306:3306'
